[package]
name = "gotiga"
version = "0.1.0"
edition = "2021"

[lib]
name = "cabinet_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
tauri-plugin-fs = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
rusqlite = { version = "0.31", features = ["bundled"] }
uuid = { version = "1", features = ["v4"] }
thiserror = "1"
reqwest = { version = "0.11", features = ["json", "stream", "multipart"] }
chrono = { version = "0.4", features = ["serde"] }
tauri-plugin-dialog = "2.6.0"
urlencoding = "2"