//! Properties that must hold for *every* match, not for a chosen one.
//!
//! The setups below are generated by a small congruential counter that lives
//! here in the test and never in the crate — the engine itself has no source of
//! chance at all, which is the point. The counter is seeded by hand, so a
//! failure names an exact seed and is reproduced by rerunning.

use battle_core::*;

/// Deterministic counter. Numbers chosen from Numerical Recipes; nothing rests
/// on their quality, only on their repeatability.
struct Roll(u32);

impl Roll {
    fn next(&mut self, upto: u32) -> u32 {
        self.0 = self.0.wrapping_mul(1_664_525).wrapping_add(1_013_904_223);
        (self.0 >> 16) % upto
    }
}

fn generate(seed: u32) -> Setup {
    let mut r = Roll(seed);
    let mut setup = Setup::default();

    for side in [Side::Keeper, Side::Player] {
        let bodies = 1 + r.next(3);
        let held = r.next(3);
        let mut taken: Vec<Cell> = Vec::new();

        for _ in 0..bodies {
            let card = CardSnapshot::new("тело", 1 + r.next(3) as i32, 2 + r.next(8) as i32, 1 + r.next(5) as i32)
                .with_armor(r.next(3) as i32)
                .with_reach(1 + r.next(3) as u8)
                .with_step(r.next(3) as u8)
                // Каждый второй умеет лечить: без этого генератор не трогает
                // новую механику, и вся эта батарея о ней ничего не скажет.
                .with_mend(if r.next(2) == 0 { 0 } else { 1 + r.next(4) as i32 });
            let base = if side == Side::Player { 3 } else { 0 };
            let cell = loop {
                let c = Cell::new(r.next(3) as u8, base + r.next(3) as u8).unwrap();
                if !taken.contains(&c) {
                    break c;
                }
            };
            taken.push(cell);
            match side {
                Side::Player => setup.player_board.push((card, cell)),
                Side::Keeper => setup.keeper_board.push((card, cell)),
            }
        }

        for _ in 0..held {
            let card = CardSnapshot::new("рука", 1 + r.next(4) as i32, 2 + r.next(7) as i32, 1 + r.next(4) as i32);
            match side {
                Side::Player => setup.player_hand.push(card),
                Side::Keeper => setup.keeper_hand.push(card),
            }
        }
    }
    setup
}

struct Run {
    state: MatchState,
    journal: Vec<Event>,
    actions: usize,
}

fn play(setup: Setup) -> Run {
    let mut state = MatchState::begin(setup);
    let mut journal = Vec::new();
    let mut actions = 0;
    while state.outcome.is_none() {
        let action = bot::choose(&state);

        // Soundness of the offered list: whatever is offered must be accepted.
        // Checked on every real position rather than on one written by hand.
        assert!(
            legal_actions(&state).contains(&action),
            "бот выбрал то, чего нет в списке законного"
        );

        let (next, events) = reduce(&state, &action).expect("законное действие отклонено");
        state = next;
        journal.extend(events);
        actions += 1;
        assert!(actions < 5_000, "партия не завершилась");
    }
    Run { state, journal, actions }
}

/// Every truth about the board that must hold at the end of any match.
fn check_board(st: &MatchState, seed: u32) {
    let mut seen: Vec<UnitId> = Vec::new();
    for (cell, id) in st.board.occupied() {
        assert!(!seen.contains(&id), "seed {seed}: тело стоит на двух клетках");
        seen.push(id);
        let u = st.unit(id).expect("на клетке несуществующее тело");
        assert!(!u.health.is_dead(), "seed {seed}: павшее тело осталось на поле");
        assert_eq!(st.board.cell_of(id), Some(cell));
    }
    for u in &st.units {
        if u.health.is_dead() {
            assert!(st.board.cell_of(u.id).is_none(), "seed {seed}: павший на поле");
        }
        assert!(u.health.current >= 0, "seed {seed}: здоровье ушло в минус");
        assert!(u.health.current <= u.health.max, "seed {seed}: здоровье выше исходного");
        assert!(u.shield >= 0, "seed {seed}: щит ушёл в минус");
    }
}

#[test]
fn five_hundred_matches_all_end_and_all_stay_consistent() {
    for seed in 0..500u32 {
        let run = play(generate(seed));

        assert!(run.state.outcome.is_some(), "seed {seed}: без исхода");
        assert!(
            matches!(run.journal.last(), Some(Event::Finished { .. })),
            "seed {seed}: журнал не кончается объявлением исхода"
        );
        assert!(run.state.round <= battle_core::state::MAX_ROUNDS + 1, "seed {seed}: сверх лимита");
        check_board(&run.state, seed);
    }
}

#[test]
fn damage_dealt_accounts_for_the_health_lost() {
    for seed in 0..200u32 {
        let run = play(generate(seed));

        let dealt: i32 = run
            .journal
            .iter()
            .filter_map(|e| match e {
                Event::Damaged { to_health, .. } => Some(*to_health),
                _ => None,
            })
            .sum();
        let restored: i32 = run
            .journal
            .iter()
            .filter_map(|e| match e {
                Event::Healed { amount, .. } => Some(*amount),
                _ => None,
            })
            .sum();
        let lost: i32 = run.state.units.iter().map(|u| u.health.max - u.health.current).sum();

        // Not equality: the last blow on a body may be larger than what was
        // left of it, and that overkill is deliberately not recorded anywhere.
        //
        // The mending term is not cosmetic. Without it this check kept passing
        // the moment healing arrived while no longer meaning anything — `dealt`
        // alone is trivially above a total that healing keeps pushing down.
        assert!(
            dealt - restored >= lost,
            "seed {seed}: нанесено {dealt}, залечено {restored}, потеряно {lost}"
        );
    }
}

#[test]
fn the_same_setup_always_produces_the_same_match() {
    for seed in 0..200u32 {
        let first = play(generate(seed));
        let again = play(generate(seed));
        assert_eq!(first.journal, again.journal, "seed {seed}: журналы разошлись");
        assert_eq!(first.state, again.state, "seed {seed}: состояния разошлись");
        assert_eq!(first.actions, again.actions);
    }
}

#[test]
fn nothing_the_legal_list_offers_is_ever_refused() {
    // The stronger form of the check inside `play`: not just the action the bot
    // took, but every action on offer, at every position of a match.
    for seed in 0..60u32 {
        let mut state = MatchState::begin(generate(seed));
        while state.outcome.is_none() {
            for action in legal_actions(&state) {
                assert!(
                    reduce(&state, &action).is_ok(),
                    "seed {seed}: предложено, но отклонено: {action:?}"
                );
            }
            let action = bot::choose(&state);
            state = reduce(&state, &action).unwrap().0;
        }
    }
}
