#!/usr/bin/env node
// Self-host the site's Google Fonts (HP2).
//
// Fetches Google's own css2 stylesheet (with a modern Chrome UA so it serves woff2 +
// unicode-range subsets), downloads every referenced woff2 into static/fonts/, and writes
// static/fonts/fonts.css — Google's CSS VERBATIM, with only the `url()`s rewritten to local
// paths. Copying their CSS means every family / weight / italic / unicode-range subset is
// preserved exactly (no guessing which the site uses), so switching from the external link
// to this file changes nothing visually — it just removes the third-party origin from the
// render path (perf) and stops leaking visitor IPs to Google (privacy).
//
// Re-run whenever the font set in app.html changes. Idempotent. All-or-nothing: if any
// download fails it throws before touching fonts.css, so a partial set can never ship.

import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = join(__dirname, '..', 'static', 'fonts');

// Must match the family/weight set in src/app.html.
const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;1,300;1,400;1,500' +
  '&family=DM+Sans:ital,opsz,wght@0,9..40,300;0,9..40,400;0,9..40,500;1,9..40,300;1,9..40,400' +
  '&family=EB+Garamond:ital,wght@0,400;0,500;1,400;1,500' +
  '&family=Fraunces:ital,opsz,wght@0,9..144,300;0,9..144,400;0,9..144,500;0,9..144,650;0,9..144,750;1,9..144,300;1,9..144,400' +
  '&family=Inter:wght@400;500;600;700' +
  '&family=Instrument+Sans:wght@400;500&display=swap';

// A recent Chrome UA — Google serves woff2 to it (older/unknown UAs get ttf/eot).
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36';

/** A stable, collision-free local filename derived from the gstatic URL path. */
function localName(url) {
  const path = new URL(url).pathname; // /s/frauncessomething/v1/abc.woff2
  return path.replace(/^\/s\//, '').replace(/[^a-zA-Z0-9.]+/g, '-');
}

async function main() {
  const cssRes = await fetch(CSS_URL, { headers: { 'User-Agent': UA } });
  if (!cssRes.ok) throw new Error(`Google Fonts CSS fetch failed: ${cssRes.status}`);
  let css = await cssRes.text();

  const urls = [...css.matchAll(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2)\)/g)].map((m) => m[1]);
  const unique = [...new Set(urls)];
  if (unique.length === 0) throw new Error('No woff2 URLs found — did Google change the format / UA?');

  await mkdir(OUT_DIR, { recursive: true });

  // Download all first (all-or-nothing) before writing the CSS.
  const files = new Map(); // remoteUrl -> localName
  for (const url of unique) {
    const name = localName(url);
    const res = await fetch(url, { headers: { 'User-Agent': UA } });
    if (!res.ok) throw new Error(`woff2 fetch failed (${res.status}): ${url}`);
    const buf = Buffer.from(await res.arrayBuffer());
    if (buf.length < 500) throw new Error(`woff2 suspiciously small (${buf.length}B): ${url}`);
    await writeFile(join(OUT_DIR, name), buf);
    files.set(url, name);
  }

  // Rewrite every gstatic url() to the local path.
  for (const [url, name] of files) {
    css = css.split(url).join(`/fonts/${name}`);
  }

  const header =
    '/* Self-hosted fonts — generated by scripts/fetch-fonts.mjs (HP2). Do not edit by hand.\n' +
    ' * Google\'s css2 output, verbatim, with url()s pointed at /fonts/*.woff2. */\n';
  await writeFile(join(OUT_DIR, 'fonts.css'), header + css);

  console.log(`Self-hosted ${files.size} woff2 files + fonts.css into static/fonts/`);
}

main().catch((e) => {
  console.error('fetch-fonts failed:', e.message);
  process.exit(1);
});
