#!/usr/bin/env node
// Self-host the site's Google Fonts (HP2).
//
// Fetches Google's own css2 stylesheet (with a modern Chrome UA so it serves woff2 +
// unicode-range subsets), downloads every referenced woff2 into static/fonts/, and writes
// static/fonts/fonts.css — Google's CSS VERBATIM, with only the `url()`s rewritten to local
// paths. Copying their CSS means every family / weight / italic / unicode-range subset is
// preserved exactly (no guessing which the site uses), so switching from the external link
// to this file changes nothing visually — it just removes the third-party origin from the
// render path (perf) and stops leaking visitor IPs to Google (privacy).
//
// Re-run whenever the font set in CSS_URL changes. Idempotent. All-or-nothing:
// if any download fails it throws before touching fonts.css, so a partial set
// can never ship. Also writes fonts-critical.css (Fraunces + DM Sans) and
// fonts-rest.css (the rest), which the layout injects after `load`.

import { mkdir, readdir, unlink, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = join(__dirname, '..', 'static', 'fonts');

// Must match the families actually used on the public site and in SITE_FONTS
// (`src/lib/fonts.ts`). Inter, the reader-picker faces, and unused axes are gone.
const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;1,300;1,400;1,500' +
  '&family=DM+Sans:ital,opsz,wght@0,9..40,300;0,9..40,400;0,9..40,500;1,9..40,300;1,9..40,400' +
  '&family=EB+Garamond:ital,wght@0,400;0,500;1,400;1,500' +
  '&family=Fraunces:ital,opsz,wght@0,9..144,300;0,9..144,400;0,9..144,500;1,9..144,300;1,9..144,400' +
  '&family=Instrument+Sans:wght@400;500;600' +
  '&family=Newsreader:ital,opsz,wght@1,16..72,400;1,16..72,500&display=swap';

const KEEP_SUBSETS = new Set(['cyrillic-ext', 'cyrillic', 'latin-ext', 'latin']);

// A recent Chrome UA — Google serves woff2 to it (older/unknown UAs get ttf/eot).
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36';

/** A stable, collision-free local filename derived from the gstatic URL path. */
function localName(url) {
  const path = new URL(url).pathname; // /s/frauncessomething/v1/abc.woff2
  return path.replace(/^\/s\//, '').replace(/[^a-zA-Z0-9.]+/g, '-');
}

/** Drop vietnamese / greek / etc. @font-face blocks. The site is EN+RU. */
function keepUsedSubsets(css) {
  const parts = css.split(/(?=\/\* [a-z0-9-]+ \*\/)/i);
  const kept = [];
  for (const part of parts) {
    const m = part.match(/^\/\* ([a-z0-9-]+) \*\//i);
    if (!m) {
      kept.push(part);
      continue;
    }
    if (KEEP_SUBSETS.has(m[1].toLowerCase())) kept.push(part);
  }
  return kept.join('').replace(/\n{3,}/g, '\n\n');
}

async function main() {
  const cssRes = await fetch(CSS_URL, { headers: { 'User-Agent': UA } });
  if (!cssRes.ok) throw new Error(`Google Fonts CSS fetch failed: ${cssRes.status}`);
  let css = keepUsedSubsets(await cssRes.text());

  const urls = [...css.matchAll(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2)\)/g)].map((m) => m[1]);
  const unique = [...new Set(urls)];
  if (unique.length === 0) throw new Error('No woff2 URLs found — did Google change the format / UA?');

  await mkdir(OUT_DIR, { recursive: true });

  // Download all first (all-or-nothing) before writing the CSS.
  const files = new Map(); // remoteUrl -> localName
  for (const url of unique) {
    const name = localName(url);
    const res = await fetch(url, { headers: { 'User-Agent': UA } });
    if (!res.ok) throw new Error(`woff2 fetch failed (${res.status}): ${url}`);
    const buf = Buffer.from(await res.arrayBuffer());
    if (buf.length < 500) throw new Error(`woff2 suspiciously small (${buf.length}B): ${url}`);
    await writeFile(join(OUT_DIR, name), buf);
    files.set(url, name);
  }

  // Rewrite every gstatic url() to the local path.
  for (const [url, name] of files) {
    css = css.split(url).join(`/fonts/${name}`);
  }

  const header =
    '/* Self-hosted fonts — generated by scripts/fetch-fonts.mjs (HP2). Do not edit by hand.\n' +
    ' * Google\'s css2 output, verbatim, with url()s pointed at /fonts/*.woff2. */\n';
  await writeFile(join(OUT_DIR, 'fonts.css'), header + css);
  await writeSplitSheets(css);

  const keepNames = new Set([
    ...files.values(),
    'fonts.css',
    'fonts-critical.css',
    'fonts-rest.css',
  ]);
  for (const name of await readdir(OUT_DIR)) {
    if (!keepNames.has(name)) await unlink(join(OUT_DIR, name));
  }

  console.log(`Self-hosted ${files.size} woff2 files + fonts.css into static/fonts/`);
}

/** Faces needed to paint the first screen (display + body). Everything else waits. */
const CRITICAL_FAMILIES = new Set(['Fraunces', 'DM Sans', 'Newsreader']);

/**
 * Split the combined Google sheet so first paint can load Fraunces + DM Sans
 * without discovering Cormorant / EB Garamond / Instrument Sans (another ~200 KB
 * of woff2 on a Slow 4G pipe next to the LCP image).
 */
export function splitFontCss(css) {
  const body = css.replace(/^\/\* Self-hosted fonts[\s\S]*?\*\/\s*/, '');
  const parts = body.split(/(?=\/\* [a-z0-9-]+ \*\/)/i);
  let critical = '';
  let rest = '';
  for (const part of parts) {
    if (!part.trim()) continue;
    const family = part.match(/font-family:\s*'([^']+)'/);
    if (family && CRITICAL_FAMILIES.has(family[1])) critical += part;
    else rest += part;
  }
  return { critical, rest };
}

async function writeSplitSheets(css) {
  const { critical, rest } = splitFontCss(css);
  const criticalHeader =
    '/* Self-hosted fonts (critical) — Fraunces + DM Sans + Newsreader. Generated by scripts/fetch-fonts.mjs. */\n';
  const restHeader =
    '/* Self-hosted fonts (deferred) — Cormorant, EB Garamond, Instrument Sans. Generated by scripts/fetch-fonts.mjs. */\n';
  await writeFile(join(OUT_DIR, 'fonts-critical.css'), criticalHeader + critical);
  await writeFile(join(OUT_DIR, 'fonts-rest.css'), restHeader + rest);
}

async function splitExisting() {
  const { readFile } = await import('node:fs/promises');
  const css = await readFile(join(OUT_DIR, 'fonts.css'), 'utf8');
  await writeSplitSheets(css);
  console.log('Wrote fonts-critical.css + fonts-rest.css from existing fonts.css');
}

const splitOnly = process.argv.includes('--split-only');
(splitOnly ? splitExisting : main)().catch((e) => {
  console.error('fetch-fonts failed:', e.message);
  process.exit(1);
});
