CREATE TABLE IF NOT EXISTS releases (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    version INTEGER GENERATED BY DEFAULT AS IDENTITY,
    file_path TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    description TEXT
);

-- Ensure only one active release at a time
CREATE UNIQUE INDEX IF NOT EXISTS idx_releases_one_active 
    ON releases (is_active) 
    WHERE is_active = TRUE;
